[workspace]
# path of the git-cliff configuration
changelog_config = "cliff.toml"
# update dependencies with `cargo update`
dependencies_update = true
# labels for the release PR
pr_labels = ["release"]
# disable git releases (handled by publish workflow)
git_release_enable = false
# run `cargo-semver-checks` to catch accidental breaking changes (enabled now
# that the crate has published releases)
semver_check = true
